{
 "title": "EMS Battery Overview",
 "tags": [ "EMS" ],
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "1m",
 "panels": [
  { "title": "Battery Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Battery Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "import \"date\"\r\nstop = v.timeRangeStop\r\nstart = date.sub(from: stop, d: 1d)\r\nfrom(bucket: \"EMS\")\r\n  |> range(start: start, stop: stop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ems_battery\" or (r[\"_measurement\"] == \"ems_battery_towers\" and r[\"Tower\"] == \"0\"))\r\n  |> sort(columns: [\"_time\"])\r\n  |> tail(n: 1)\r\n  |> drop(columns: [\"_start\", \"_stop\", \"battery\", \"_measurement\", \"_time\", \"Tower\"])\r\n  |> map(fn: (r) => ({r with val: string(v: r[\"_value\"])}))\r\n  |> drop(columns: [\"_value\"])\r\n  |> group()\r\n  |> filter(fn: (r) => \r\n         r[\"_field\"] == \"BmsSerialNumber\" \r\n      or r[\"_field\"] == \"BmsSoftwareVersion\"\r\n      or r[\"_field\"] == \"Capacity\"\r\n      or r[\"_field\"] == \"NumberOfModulesPerTower\"\r\n      or r[\"_field\"] == \"NumberOfTowers\"\r\n      or r[\"_field\"] == \"RackNumberOfCellsInSeriesPerModule\"\r\n  )\r\n"
    }
   ]
  },
  {
   "title": "Battery Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 1 },
   "targets": [
    {
     "query": "import \"date\"\r\nstop = v.timeRangeStop\r\nstart = date.sub(from: stop, d: 1d)\r\nfrom(bucket: \"EMS\")\r\n  |> range(start: start, stop: stop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ems_battery\" or (r[\"_measurement\"] == \"ems_battery_towers\" and r[\"Tower\"] == \"0\"))\r\n  |> sort(columns: [\"_time\"])\r\n  |> tail(n: 1)\r\n  |> drop(columns: [\"_start\", \"_stop\", \"battery\", \"_measurement\", \"_time\", \"Tower\"])\r\n  |> map(fn: (r) => ({r with val: string(v: r[\"_value\"])}))\r\n  |> drop(columns: [\"_value\"])\r\n  |> group()\r\n  |> filter(fn: (r) => \r\n         r[\"_field\"] == \"AvarageCellVoltage\" \r\n      or r[\"_field\"] == \"MaxCellVoltage\"\r\n      or r[\"_field\"] == \"MinCellVoltage\"\r\n      or r[\"_field\"] == \"NoOfCycles\"\r\n      or r[\"_field\"] == \"RemainingCapacity\"\r\n      or r[\"_field\"] == \"UsableCapacity\"\r\n      or r[\"_field\"] == \"Soh\"\r\n  )"
    }
   ]
  },
  {
   "title": "State of Charge",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\r\nstop = v.timeRangeStop\r\nstart = date.sub(from: stop, d: 1d)\r\nfrom(bucket: \"EMS\")\r\n  |> range(start: start, stop: stop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ems_battery_towers\" and r[\"_field\"] == \"Soc\")\r\n  |> sort(columns: [\"_time\"])\r\n  |> tail(n: 1)\r\n  |> drop(columns: [\"_start\", \"_stop\", \"battery\", \"_measurement\", \"_time\", \"Tower\"])\r\n"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\r\nstop = v.timeRangeStop\r\nstart = date.sub(from: stop, d: 1d)\r\nfrom(bucket: \"EMS\")\r\n  |> range(start: start, stop: stop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ems_battery_towers\" and r[\"_field\"] == \"Voltage\")\r\n  |> sort(columns: [\"_time\"])\r\n  |> tail(n: 1)\r\n  |> drop(columns: [\"_start\", \"_stop\", \"battery\", \"_measurement\", \"_time\", \"Tower\"])\r\n"
    }
   ]
  },
  {
   "title": "Current",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\r\nstop = v.timeRangeStop\r\nstart = date.sub(from: stop, d: 1d)\r\nfrom(bucket: \"EMS\")\r\n  |> range(start: start, stop: stop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ems_battery_towers\" and r[\"_field\"] == \"Current\")\r\n  |> sort(columns: [\"_time\"])\r\n  |> tail(n: 1)\r\n  |> drop(columns: [\"_start\", \"_stop\", \"battery\", \"_measurement\", \"_time\", \"Tower\"])\r\n"
    }
   ]
  },
  { "title": "Modules", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Modules (In stacking sequence top: 0)",
   "type": "table",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 10 },
   "targets": [
    {
     "query": "import \"date\"\r\nimport \"math\"\r\nimport \"join\"\r\nstop = v.timeRangeStop\r\nstart = date.sub(from: stop, d: 1d)\r\ncv =\r\n  from(bucket: \"EMS\")\r\n    |> range(start: start, stop: stop)\r\n    |> filter(fn: (r) => r[\"_measurement\"] == \"ems_battery_cells\" and r[\"_field\"] == \"Voltage\")\r\n    |> sort(columns: [\"_time\"])\r\n    |> tail(n: 1)\r\n    |> drop(columns: [\"_start\", \"_stop\", \"battery\", \"_measurement\", \"_time\", \"Tower\"])\r\n    |> sort(columns: [\"_Module\"])\r\n    |> group(columns: [\"Module\"])\r\n    |> sum()\r\n    |> map(fn: (r) => ({r with Voltage: float(v: r._value)/1000.0}))\r\n    |> drop(columns: [\"_value\"])\r\n    |> group()\r\n\r\nmt =\r\n  from(bucket: \"EMS\")\r\n    |> range(start: start, stop: stop)\r\n    |> filter(fn: (r) => r[\"_measurement\"] == \"ems_battery_modules\")\r\n    |> sort(columns: [\"_time\"])\r\n    |> tail(n: 1)\r\n    |> drop(columns: [\"_start\", \"_stop\", \"battery\", \"_measurement\", \"_time\", \"Tower\"])\r\n    |> sort(columns: [\"_Module\"])\r\n    |> group(columns: [\"Module\"])\r\n    |> mean()\r\n    |> map(fn: (r) => ({r with Temperature: math.round(x: r._value * 10.0) / 100.0}))\r\n    |> drop(columns: [\"_value\"])\r\n    |> group()\r\n\r\nms =\r\n  from(bucket: \"EMS\")\r\n    |> range(start: start, stop: stop)\r\n    |> filter(fn: (r) => r[\"_measurement\"] == \"ems_battery_modules\")\r\n    |> sort(columns: [\"_time\"])\r\n    |> tail(n: 1)\r\n    |> drop(columns: [\"_start\", \"_stop\", \"battery\", \"_measurement\", \"_time\", \"Tower\", \"_field\", \"_value\"])\r\n    |> sort(columns: [\"_Module\"])\r\n    |> tail(n: 1)\r\n    |> group()\r\n\r\nmst =\r\n    join.inner(left: ms, \r\n               right: mt, \r\n               on: (l, r) => l.Module == r.Module,\r\n               as: (l, r) => ({l with Temperature: r.Temperature}) \r\n              )\r\n\r\nmstv =\r\n    join.inner(left: mst, \r\n               right: cv, \r\n               on: (l, r) => l.Module == r.Module,\r\n               as: (l, r) => ({l with Voltage: r.Voltage}) \r\n              )\r\nmstv"
    }
   ]
  }
 ]
}